// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuhasebeTakip2.App.Data;

#nullable disable

namespace MuhasebeTakip2.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323070929_KullaniciRolEkle")]
    partial class KullaniciRolEkle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Avans")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IseGirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Maas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanAvans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CalisanId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.HasIndex("FirmaId");

                    b.ToTable("CalisanAvanslari");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CariKart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VergiNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("CariKartlar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.KasaHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CariKartId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CariKartId");

                    b.HasIndex("FirmaId");

                    b.ToTable("KasaHareketleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriIs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Gelir")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsAdi")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("MusteriId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriIsler");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriMasraf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MusteriIsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("MusteriIsId");

                    b.ToTable("MusteriMasraflar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.StokHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("TEXT");

                    b.Property<int>("StokUrunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("StokUrunId");

                    b.ToTable("StokHareketleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.StokUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("StokUrunler");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Calisan", b =>
                {
                    b.HasOne("Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanAvans", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Calisan", "Calisan")
                        .WithMany("Avanslar")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Calisan");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CariKart", b =>
                {
                    b.HasOne("Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.KasaHareket", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.CariKart", "CariKart")
                        .WithMany()
                        .HasForeignKey("CariKartId");

                    b.HasOne("Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("CariKart");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Kullanici", b =>
                {
                    b.HasOne("Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Musteri", b =>
                {
                    b.HasOne("Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriIs", b =>
                {
                    b.HasOne("Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.HasOne("MuhasebeTakip2.App.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriMasraf", b =>
                {
                    b.HasOne("Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.HasOne("MuhasebeTakip2.App.Models.MusteriIs", "MusteriIs")
                        .WithMany("Masraflar")
                        .HasForeignKey("MusteriIsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("MusteriIs");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.StokHareket", b =>
                {
                    b.HasOne("Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.HasOne("MuhasebeTakip2.App.Models.StokUrun", "StokUrun")
                        .WithMany()
                        .HasForeignKey("StokUrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("StokUrun");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.StokUrun", b =>
                {
                    b.HasOne("Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Calisan", b =>
                {
                    b.Navigation("Avanslar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriIs", b =>
                {
                    b.Navigation("Masraflar");
                });
#pragma warning restore 612, 618
        }
    }
}
