// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuhasebeTakip2.App.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MuhasebeTakip2.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715095640_AddOdemeEmailBildirimSistemi")]
    partial class AddOdemeEmailBildirimSistemi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Avans")
                        .HasColumnType("numeric");

                    b.Property<string>("AyrilisNotu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AyrilisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IseGirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Maas")
                        .HasColumnType("numeric");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanAvans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ArsivlendiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("CalisanId")
                        .HasColumnType("integer");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.HasIndex("FirmaId");

                    b.ToTable("CalisanAvanslari");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanMaasArsiv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("CalisanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DonemBaslangic")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DonemBitis")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("KalanMaas")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ToplamAvans")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ToplamMaas")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("CalisanMaasArsivleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanPuantaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CalisanId")
                        .HasColumnType("integer");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("Not")
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.HasIndex("FirmaId");

                    b.ToTable("CalisanPuantajlari");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CariKart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("ArsivNotu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArsivTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("CariKartlar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Cek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResimYolu")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("Cekler");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.EkDosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Boyut")
                        .HasColumnType("bigint");

                    b.Property<int?>("CariKartId")
                        .HasColumnType("integer");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("IcerikTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CariKartId");

                    b.HasIndex("FaturaId");

                    b.HasIndex("FirmaId");

                    b.ToTable("EkDosyalar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AraToplam")
                        .HasColumnType("numeric");

                    b.Property<string>("ArsivNotu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArsivTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CariKartId")
                        .HasColumnType("integer");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GenelToplam")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KdvToplam")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OdenenToplam")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VadeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CariKartId");

                    b.HasIndex("FirmaId", "FaturaNo")
                        .IsUnique();

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.FaturaKalem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("AraToplam")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric");

                    b.Property<int>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GenelToplam")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KdvTutar")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.ToTable("FaturaKalemleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.FaturaNumaraAyari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiraUzunlugu")
                        .HasColumnType("integer");

                    b.Property<int>("SonNumara")
                        .HasColumnType("integer");

                    b.Property<bool>("YilEkle")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("FaturaNumaraAyarlari");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MenuCalisanlar")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuCariKartlar")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuCekler")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuKasa")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuMaliyet")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuMusteriler")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuOdemeler")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuRaporlar")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuStoklar")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.IslemGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EskiDeger")
                        .HasColumnType("text");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("IpAdresi")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("Modul")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TarayiciBilgisi")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YeniDeger")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId", "Modul");

                    b.HasIndex("FirmaId", "Tarih");

                    b.ToTable("IslemGecmisleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.KasaHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CariKartId")
                        .HasColumnType("integer");

                    b.Property<int?>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CariKartId");

                    b.HasIndex("FaturaId");

                    b.HasIndex("FirmaId");

                    b.ToTable("KasaHareketleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailDogrulandiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OdemeEmailBildirimiAktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SifreSifirlamaKodGecerlilik")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SifreSifirlamaKodu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MaliyetKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ArkalikMaliyeti")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BantlamaMaliyeti")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BirimMaliyet")
                        .HasColumnType("numeric");

                    b.Property<string>("DetayJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HesapTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MalzemeMaliyeti")
                        .HasColumnType("numeric");

                    b.Property<string>("OkunanMetin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PlakaMaliyeti")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ToplamMaliyet")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UretimAdedi")
                        .HasColumnType("numeric");

                    b.Property<string>("UretimAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("MaliyetKayitlari");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("ArsivNotu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArsivTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriIs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Gelir")
                        .HasColumnType("numeric");

                    b.Property<string>("IsAdi")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriIsler");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriMasraf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<int>("MusteriIsId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("MusteriIsId");

                    b.ToTable("MusteriMasraflar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.OdemeBildirimGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BasariliMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("BildirimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BildirimTuru")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("HataMesaji")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HedefEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeDonemi")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("OdemePlaniId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("OdemePlaniId");

                    b.HasIndex("FirmaId", "OdemePlaniId", "BildirimTarihi");

                    b.HasIndex("FirmaId", "KullaniciId", "OdemePlaniId", "BildirimTuru", "OdemeDonemi");

                    b.ToTable("OdemeBildirimGecmisleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.OdemeHareketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<int>("KalanTaksitSayisi")
                        .HasColumnType("integer");

                    b.Property<int>("OdemePlaniId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OlusturanKullaniciAdi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("OdemePlaniId");

                    b.HasIndex("FirmaId", "OdemePlaniId", "OdemeTarihi");

                    b.ToTable("OdemeHareketleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.OdemePlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AylikOdemeTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("BildirimAktifMi")
                        .HasColumnType("boolean");

                    b.Property<int>("BildirimGunu")
                        .HasColumnType("integer");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IlkOdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KalanTaksitSayisi")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("OdemeGunu")
                        .HasColumnType("integer");

                    b.Property<int>("OdemeTuru")
                        .HasColumnType("integer");

                    b.Property<string>("OlusturanKullaniciAdi")
                        .HasColumnType("text");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OtomatikTaksitDusur")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SonOdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SonOdemeYapildiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SonrakiOdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ToplamTaksitSayisi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("FirmaId", "AktifMi", "SonrakiOdemeTarihi");

                    b.ToTable("OdemePlanlari");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.StokHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KoliAdedi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KoliFiyat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<int>("StokUrunId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("StokUrunId");

                    b.ToTable("StokHareketleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.StokUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("ArsivNotu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArsivTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MinStokSeviyesi")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("StokUrunler");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Calisan", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanAvans", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Calisan", "Calisan")
                        .WithMany("Avanslar")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Calisan");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanPuantaj", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Calisan", "Calisan")
                        .WithMany()
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CariKart", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Cek", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.EkDosya", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.CariKart", "CariKart")
                        .WithMany()
                        .HasForeignKey("CariKartId");

                    b.HasOne("MuhasebeTakip2.App.Models.Fatura", "Fatura")
                        .WithMany()
                        .HasForeignKey("FaturaId");

                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CariKart");

                    b.Navigation("Fatura");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Fatura", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.CariKart", "CariKart")
                        .WithMany()
                        .HasForeignKey("CariKartId");

                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("CariKart");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.FaturaKalem", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Fatura", "Fatura")
                        .WithMany("Kalemler")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.FaturaNumaraAyari", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.IslemGecmisi", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.KasaHareket", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.CariKart", "CariKart")
                        .WithMany()
                        .HasForeignKey("CariKartId");

                    b.HasOne("MuhasebeTakip2.App.Models.Fatura", "Fatura")
                        .WithMany()
                        .HasForeignKey("FaturaId");

                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("CariKart");

                    b.Navigation("Fatura");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Kullanici", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MaliyetKaydi", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Musteri", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriIs", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.HasOne("MuhasebeTakip2.App.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriMasraf", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.HasOne("MuhasebeTakip2.App.Models.MusteriIs", "MusteriIs")
                        .WithMany("Masraflar")
                        .HasForeignKey("MusteriIsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("MusteriIs");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.OdemeBildirimGecmisi", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuhasebeTakip2.App.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuhasebeTakip2.App.Models.OdemePlani", "OdemePlani")
                        .WithMany()
                        .HasForeignKey("OdemePlaniId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("Kullanici");

                    b.Navigation("OdemePlani");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.OdemeHareketi", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuhasebeTakip2.App.Models.OdemePlani", "OdemePlani")
                        .WithMany("Hareketler")
                        .HasForeignKey("OdemePlaniId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("OdemePlani");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.OdemePlani", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.StokHareket", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.HasOne("MuhasebeTakip2.App.Models.StokUrun", "StokUrun")
                        .WithMany()
                        .HasForeignKey("StokUrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("StokUrun");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.StokUrun", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Calisan", b =>
                {
                    b.Navigation("Avanslar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Fatura", b =>
                {
                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriIs", b =>
                {
                    b.Navigation("Masraflar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.OdemePlani", b =>
                {
                    b.Navigation("Hareketler");
                });
#pragma warning restore 612, 618
        }
    }
}
