// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuhasebeTakip2.App.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MuhasebeTakip2.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413125140_CalisanPasifArsivSistemi")]
    partial class CalisanPasifArsivSistemi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Avans")
                        .HasColumnType("numeric");

                    b.Property<string>("AyrilisNotu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AyrilisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IseGirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Maas")
                        .HasColumnType("numeric");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanArsiv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("AyrilisNotu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("AyrilisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EskiCalisanId")
                        .HasColumnType("integer");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IseGirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Maas")
                        .HasColumnType("numeric");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("CalisanArsivleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanAvans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ArsivlendiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("CalisanId")
                        .HasColumnType("integer");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.HasIndex("FirmaId");

                    b.ToTable("CalisanAvanslari");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanMaasArsiv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("CalisanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DonemBaslangic")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DonemBitis")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("KalanMaas")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ToplamAvans")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ToplamMaas")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("CalisanMaasArsivleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanPuantaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CalisanId")
                        .HasColumnType("integer");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("Not")
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.HasIndex("FirmaId");

                    b.ToTable("CalisanPuantajlari");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CariKart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("CariKartlar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Cek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResimYolu")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("Cekler");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MenuCalisanlar")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuCariKartlar")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuCekler")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuKasa")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuMaliyet")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuMusteriler")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuRaporlar")
                        .HasColumnType("boolean");

                    b.Property<bool>("MenuStoklar")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.KasaHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CariKartId")
                        .HasColumnType("integer");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CariKartId");

                    b.HasIndex("FirmaId");

                    b.ToTable("KasaHareketleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriIs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Gelir")
                        .HasColumnType("numeric");

                    b.Property<string>("IsAdi")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriIsler");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriMasraf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<int>("MusteriIsId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("MusteriIsId");

                    b.ToTable("MusteriMasraflar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.StokHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<int>("StokUrunId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("StokUrunId");

                    b.ToTable("StokHareketleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.StokUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("StokUrunler");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Calisan", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanArsiv", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanAvans", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Calisan", "Calisan")
                        .WithMany("Avanslar")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Calisan");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanPuantaj", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Calisan", "Calisan")
                        .WithMany()
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CariKart", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Cek", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.KasaHareket", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.CariKart", "CariKart")
                        .WithMany()
                        .HasForeignKey("CariKartId");

                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("CariKart");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Kullanici", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Musteri", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriIs", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.HasOne("MuhasebeTakip2.App.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriMasraf", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.HasOne("MuhasebeTakip2.App.Models.MusteriIs", "MusteriIs")
                        .WithMany("Masraflar")
                        .HasForeignKey("MusteriIsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("MusteriIs");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.StokHareket", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.HasOne("MuhasebeTakip2.App.Models.StokUrun", "StokUrun")
                        .WithMany()
                        .HasForeignKey("StokUrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("StokUrun");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.StokUrun", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Calisan", b =>
                {
                    b.Navigation("Avanslar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.MusteriIs", b =>
                {
                    b.Navigation("Masraflar");
                });
#pragma warning restore 612, 618
        }
    }
}
