// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuhasebeTakip2.App.Data;

#nullable disable

namespace MuhasebeTakip2.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304132659_AddCalisanAvans")]
    partial class AddCalisanAvans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Avans")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IseGirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Maas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanAvans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("CalisanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.ToTable("CalisanAvanslari");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CariKart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VergiNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CariKartlar");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.KasaHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CariKartId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CariKartId");

                    b.ToTable("KasaHareketleri");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.CalisanAvans", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.Calisan", "Calisan")
                        .WithMany("Avanslar")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.KasaHareket", b =>
                {
                    b.HasOne("MuhasebeTakip2.App.Models.CariKart", "CariKart")
                        .WithMany()
                        .HasForeignKey("CariKartId");

                    b.Navigation("CariKart");
                });

            modelBuilder.Entity("MuhasebeTakip2.App.Models.Calisan", b =>
                {
                    b.Navigation("Avanslar");
                });
#pragma warning restore 612, 618
        }
    }
}
